name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy Railway
      uses: bervProject/railway-deploy@main
      with:
        railway_token:  ${{ secrets.RAILWAY_TOKEN }}
        service:  ${{ secrets.RAILWAY_SERVICE }}
      env:
        SONAR_JDBC_URL: ${{ secrets.SONAR_JDBC_URL }}
        SONAR_JDBC_USERNAME: ${{ secrets.SONAR_JDBC_USERNAME }}
        SONAR_JDBC_PASSWORD: ${{ secrets.SONAR_JDBC_PASSWORD }}
      run: |
          railway up --detach --build-only
          docker-compose -f docker-compose.yml up -d
